name: portafolio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  icons_plus: ^5.0.0
  intl: ^0.18.1
  provider: ^6.1.2
  responsive_framework: ^1.4.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/apps/

flutter_intl:
  enabled: true
